# -*- coding: utf-8 -*-
"""Data Visualization with Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18rLsJAWP28m3j0JLEl6qt2p_rfnT4ZDE
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount("/content/drive")

# %cd /content/drive/MyDrive/MatePythonHomework

sales_data = pd.read_csv("sales_data_updated.csv")
sales_data.head()

"""###*Побудуй гістограму для візуалізації розподілу ціни продажу (sales). Проаналізуй, які продажі зустрічаються найчастіше, який характер розподілу значень загалом.*"""

plt.hist(sales_data["sales"], bins=15, color="violet")
plt.title("Distribution of Sales")  # Title of the histogram
plt.xlabel("Sales ($)")  # X-axis label
plt.ylabel("Frequency")  # Y-axis label
plt.show()

"""###Найчастіше зустрічаються продажі приблизно в діапазоні 200–230 .Також помітні часті продажі в діапазонах приблизно 60–80 і 110–130 . Продажі в проміжках близько 90–100  та 160–190 трапляються рідше. Розподіл не є рівномірним і не схожий на нормальний, бо має кілька виражених піків.

###*Створи лінійний графік, який показує зміну продажів (sales) у часі (order_date). Перед цим потрібно переконатись у тому, що стовпчик order_date має відповідний тип даних. Це допоможе зрозуміти тенденцію покупок протягом зазначеного періоду. Якою є ця тенденція згідно з графіком?*
"""

sales_data["order_date"] = pd.to_datetime(sales_data["order_date"])
monthly_sales = sales_data.resample("M", on="order_date")["sales"].sum().reset_index()

monthly_sales = monthly_sales.sort_values("order_date")
plt.plot(monthly_sales["order_date"], monthly_sales["sales"], marker="o", color="brown")
plt.title("Sales by month")  # Title of the graph
plt.xlabel("Date")  # X-axis label
plt.ylabel("Sales")  # Y-axis label
plt.show()

"""###Продажі протягом року коливаються, але загалом видно поступове зростання після весни. Найвищі піки продажів спостерігаються приблизно у травні та липні. Наприкінці року рівень продажів залишається вищим, ніж на початку року, тому можна сказати, що загальна тенденція є зростаючою, хоча з сильними коливаннями.

###*Побудуй стовпчастий графік, що показує кількість замовлень за категоріями товарів (product_category). Використовуй групування даних. Яка категорія найбільш популярна? Яка найменш популярна?*
"""

plt.figure(figsize=(10, 7))
order_by_product_category = sales_data.groupby("product_category")["customer_id"].size().sort_values()
plt.bar(order_by_product_category.index, order_by_product_category.values, color="green")

plt.title("Orders by Category")  # Title of the graph
plt.xlabel("Category")  # X-axis label
plt.ylabel("Count")  # Y-axis label
plt.show()

"""###Найбільше замовлень припадає на категорію Fashion, тому вона є найпопулярнішою. Найменше замовлень має категорія Electronic, отже вона є найменш популярною. Загалом видно, що кількість замовлень суттєво відрізняється між категоріями.

###*Створи діаграму розсіювання для візуалізації взаємозв'язку між прибутком (profit) та загальною сумою продажу (sales). Подумай, чи є зв'язок між цими показниками і який характер цього взаємозв'язку.*
"""

plt.figure(figsize=(10, 7))

plt.scatter(sales_data["sales"], sales_data["profit"], alpha=0.5)

plt.title("Sales vs Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.show()

"""###Між sales і profit спостерігається позитивний зв’язок: зі збільшенням продажів зазвичай зростає і прибуток.

###*Створи масив графіків (2x2) з попередніх візуалізацій, щоб на одному малюнку побачити всі графіки та порівняти їх.*
"""

fig, ax = plt.subplots(2, 2, figsize=(15, 10))

ax[0, 0].hist(sales_data["sales"], bins=15, color="violet")
ax[0, 0].set_title("Distribution of Sales")  # Title of the histogram
ax[0, 0].set_xlabel("Sales ($)")  # X-axis label
ax[0, 0].set_ylabel("Frequency")  # Y-axis label


ax[0, 1].plot(monthly_sales["order_date"], monthly_sales["sales"], marker="o", color="brown")
ax[0, 1].set_title("Sales by month")  # Title of the graph
ax[0, 1].set_xlabel("Date")  # X-axis label
ax[0, 1].set_ylabel("Sales")  # Y-axis label

order_by_product_category = sales_data.groupby("product_category")["customer_id"].size().sort_values()
ax[1, 0].bar(order_by_product_category.index, order_by_product_category.values, color="green")
ax[1, 0].set_title("Orders by Category")  # Title of the graph
ax[1, 0].set_xlabel("Category")  # X-axis label
ax[1, 0].set_ylabel("Count")  # Y-axis label

ax[1, 1].scatter(sales_data["sales"], sales_data["profit"], alpha=0.5)
ax[1, 1].set_title("Sales vs Profit")
ax[1, 1].set_xlabel("Sales")
ax[1, 1].set_ylabel("Profit")
plt.show()

"""###На одному зображені показано: розподіл продажів, зміну продажів у часі, кількість замовлень за категоріями та зв’язок між продажами і прибутком. Найпопулярнішою категорією є **Fashion**, найменш популярною — **Electronic**. Продажі мають кілька частих діапазонів, у часі спостерігаються коливання з окремими піками. Між **sales** і **profit** видно позитивний зв’язок: зі збільшенням продажів зазвичай зростає прибуток."""