# -*- coding: utf-8 -*-
"""Working with NumPy and Pandas. Part 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0zlGOWjL4VyfzsKbXtGIHZaoTV8169W
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount("/content/drive")

# %cd /content/drive/MyDrive/MatePythonHomework/

adult_df = pd.read_csv("adult.csv")
adult_df = adult_df.replace(r"^\s*\?\s*$", np.nan, regex=True).dropna().reset_index(drop=True)
adult_df.head()

more_50 = adult_df[adult_df["salary"] == ">50K"]
less_equal_50 = adult_df[adult_df["salary"] == "<=50K"]

# статистика для >50K
more_50_mean_age = more_50["age"].mean()
more_50_std_age = more_50["age"].std()

# статистика для <=50K
less_equal_50_mean_age = less_equal_50["age"].mean()
less_equal_50_std_age = less_equal_50["age"].std()


print("People earning >50K:")
print("Mean age:", round(more_50_mean_age, 2))
print("Standard deviation:", round(more_50_std_age, 2))

print("-----------------------------------------------")

print("People earning <=50K:")
print("Mean age:", round(less_equal_50_mean_age, 2))
print("Standard deviation:", round(less_equal_50_std_age, 2))

# створюємо числову колонку для зарплати
# <=50K = 0
# >50K = 1
adult_df["salary_numeric"] = 0
adult_df.loc[adult_df["salary"] == ">50K", "salary_numeric"] = 1

# кореляція між віком і зарплатою
correlation = adult_df["age"].corr(adult_df["salary_numeric"])

print("Correlation between age and salary:", round(correlation, 3))

# аналіз кореляції
if correlation > 0:
    print("There is a positive correlation: older people are more likely to earn >50K.")
elif correlation < 0:
    print("There is a negative correlation: younger people are more likely to earn >50K.")
else:
  print("There is no correlation between age and salary.")